//
//  KCSDeltaSetCacheTests.swift
//  KinveyKit
//
//  Created by Victor Barros on 2015-09-21.
//  Copyright © 2015 Kinvey. All rights reserved.
//

import UIKit

class KCSDeltaSetCacheTests: KCSTestCase {
    
    var collection: KCSCollection!
    var store: KCSBackgroundAppdataStore!
    var storeNoCache: KCSBackgroundAppdataStore!
    var query: KCSQuery!
    
    let timeout = NSTimeInterval(120)
    
    static var token: dispatch_once_t = 0
    
    override func setUp() {
        super.setUp()
        
        setupKCS()
        createAutogeneratedUser()
        
        query = KCSQuery(onField: "_acl.creator", withExactMatchForValue: KCSUser.activeUser())
        
        collection = KCSCollection(fromString: "city", ofClass: City.self)
        store = KCSBackgroundAppdataStore(
            collection: collection,
            options: [
                KCSStoreKeyCachePolicy: KCSCachePolicy.NetworkFirst.rawValue,
            ]
        )
        store.enableDataSetCaching = true
        
        storeNoCache = KCSBackgroundAppdataStore(
            collection: collection,
            options: [
                KCSStoreKeyCachePolicy: KCSCachePolicy.None.rawValue,
            ]
        )
        
        dispatch_once(&KCSDeltaSetCacheTests.token) {
            var cities: [City] = []
            for _ in 1...10 {
                cities.append(City(name: "Boston"))
            }
            do {
                weak var expectationSave = self.expectationWithDescription("save")
                
                self.storeNoCache.saveObject(
                    cities,
                    withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                        XCTAssertNotNil(results)
                        XCTAssertNil(error)
                        
                        expectationSave?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationSave = nil
                }
            }
        }
    }
    
    override func tearDown() {
        if let user = KCSUser.activeUser() {
            weak var expectationRemove = expectationWithDescription("remove")
            
            user.removeWithCompletionBlock({ (results: [AnyObject]!, error: NSError!) -> Void in
                expectationRemove?.fulfill()
            })
            
            waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationRemove = nil
            }
            
            user.logout()
        }
        
        super.tearDown()
    }
    
    func testMeasureQuery() {
        measureBlock { () -> Void in
            weak var expectationQuery = self.expectationWithDescription("query")
            
            self.store.queryWithQuery(
                self.query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery = nil
            }
        }
    }
    
    func testNoDeltaChanges() {
        do {
            weak var expectationQuery = self.expectationWithDescription("query")
            
            store.queryWithQuery(
                query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationQuery = nil
            }
        }
        
        KCSObjectCache.setDeltaCacheBlock({ (delta: [NSObject : AnyObject]!, deletes: [NSObject : AnyObject]!, time: NSTimeInterval) -> Void in
            XCTAssertEqual(0, delta.count)
            XCTAssertEqual(0, deletes.count)
        })
        measureBlock { () -> Void in
            weak var expectationQuery2 = self.expectationWithDescription("query2")
            
            self.store.queryWithQuery(
                self.query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery2?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery2 = nil
            }
        }
    }
    
    func testDeltaCreate1NewRecord() {
        do {
            weak var expectationQuery = self.expectationWithDescription("query")
            
            store.queryWithQuery(
                query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationQuery = nil
            }
        }
        
        KCSObjectCache.setDeltaCacheBlock({ (delta: [NSObject : AnyObject]!, deletes: [NSObject : AnyObject]!, time: NSTimeInterval) -> Void in
            XCTAssertEqual(1, delta.count)
            XCTAssertEqual(0, deletes.count)
        })
        measureBlock { () -> Void in
            do {
                weak var expectationSave = self.expectationWithDescription("save")
                
                let city = City(name: "Cambridge")
                self.storeNoCache.saveObject(
                    city,
                    withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                        XCTAssertNotNil(results)
                        XCTAssertNil(error)
                        
                        expectationSave?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationSave = nil
                }
            }
            
            weak var expectationQuery2 = self.expectationWithDescription("query2")
            
            self.store.queryWithQuery(
                self.query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery2?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery2 = nil
            }
        }
    }
    
    func testDeltaDelete1Record() {
        var cities: [City] = []
        for _ in 1...10 {
            weak var expectationSave = self.expectationWithDescription("save")
            
            let city = City(name: "Cambridge")
            self.storeNoCache.saveObject(
                city,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    cities.append(results.first as! City)
                    
                    expectationSave?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationSave = nil
            }
        }
        
        do {
            weak var expectationQuery = self.expectationWithDescription("query")
            
            store.queryWithQuery(
                query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery = nil
            }
        }
        
        var count = 0
        KCSObjectCache.setDeltaCacheBlock({ (delta: [NSObject : AnyObject]!, deletes: [NSObject : AnyObject]!, time: NSTimeInterval) -> Void in
            XCTAssertEqual(0, delta.count)
            XCTAssertEqual(1, deletes.count)
        })
        measureBlock { () -> Void in
            do {
                weak var expectationDelete = self.expectationWithDescription("delete")
                
                self.storeNoCache.removeObject(
                    cities[count++],
                    withCompletionBlock: { (count: UInt, error: NSError!) -> Void in
                        XCTAssertEqual(1, count)
                        XCTAssertNil(error)
                        
                        expectationDelete?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationDelete = nil
                }
            }
            
            weak var expectationQuery2 = self.expectationWithDescription("query2")
            
            self.store.queryWithQuery(
                self.query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery2?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery2 = nil
            }
        }
    }
    
    func testDeltaUpdate1Record() {
        weak var expectationSave = self.expectationWithDescription("save")
        
        var city = City(name: "Cambridge")
        storeNoCache.saveObject(
            city,
            withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNotNil(results)
                XCTAssertNil(error)
                
                city = results.first as! City
                
                expectationSave?.fulfill()
            },
            withProgressBlock: nil
        )
        
        self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
            expectationSave = nil
        }
        
        do {
            weak var expectationQuery = self.expectationWithDescription("query")
            
            store.queryWithQuery(
                query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationQuery = nil
            }
        }
        
        KCSObjectCache.setDeltaCacheBlock({ (delta: [NSObject : AnyObject]!, deletes: [NSObject : AnyObject]!, time: NSTimeInterval) -> Void in
            XCTAssertEqual(1, delta.count)
            XCTAssertEqual(0, deletes.count)
        })
        measureBlock { () -> Void in
            do {
                weak var expectationUpdate = self.expectationWithDescription("update")
                
                city.name = "Newport"
                self.storeNoCache.saveObject(
                    city,
                    withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                        XCTAssertNotNil(results)
                        XCTAssertNil(error)
                        
                        expectationUpdate?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationUpdate = nil
                }
            }
            
            weak var expectationQuery2 = self.expectationWithDescription("query2")
            
            self.store.queryWithQuery(
                self.query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery2?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery2 = nil
            }
        }
    }
    
    func testDeltaCreateUpdateDelete1Record() {
        var cities: [City] = []
        for _ in 1...10 {
            weak var expectationSave = self.expectationWithDescription("save")
            
            let city = City(name: "Cambridge")
            self.storeNoCache.saveObject(
                city,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    cities.append(results.first as! City)
                    
                    expectationSave?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationSave = nil
            }
        }
        
        weak var expectationSave = self.expectationWithDescription("save")
        
        var city = City(name: "Cambridge")
        storeNoCache.saveObject(
            city,
            withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNotNil(results)
                XCTAssertNil(error)
                
                city = results.first as! City
                
                expectationSave?.fulfill()
            },
            withProgressBlock: nil
        )
        
        self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
            expectationSave = nil
        }
        
        do {
            weak var expectationQuery = self.expectationWithDescription("query")
            
            store.queryWithQuery(
                query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(timeout) { (error: NSError?) -> Void in
                expectationQuery = nil
            }
        }
        
        var count = 0
        KCSObjectCache.setDeltaCacheBlock({ (delta: [NSObject : AnyObject]!, deletes: [NSObject : AnyObject]!, time: NSTimeInterval) -> Void in
            XCTAssertEqual(2, delta.count)
            XCTAssertEqual(1, deletes.count)
        })
        measureBlock { () -> Void in
            do {
                weak var expectationSave = self.expectationWithDescription("save")
                
                let city = City(name: "Cambridge")
                self.storeNoCache.saveObject(
                    city,
                    withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                        XCTAssertNotNil(results)
                        XCTAssertNil(error)
                        
                        expectationSave?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationSave = nil
                }
            }
            
            do {
                weak var expectationUpdate = self.expectationWithDescription("update")
                
                city.name = "Newport"
                self.storeNoCache.saveObject(
                    city,
                    withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                        XCTAssertNotNil(results)
                        XCTAssertNil(error)
                        
                        expectationUpdate?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationUpdate = nil
                }
            }
            
            do {
                weak var expectationDelete = self.expectationWithDescription("delete")
                
                self.storeNoCache.removeObject(
                    cities[count++],
                    withCompletionBlock: { (count: UInt, error: NSError!) -> Void in
                        XCTAssertEqual(1, count)
                        XCTAssertNil(error)
                        
                        expectationDelete?.fulfill()
                    },
                    withProgressBlock: nil
                )
                
                self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                    expectationDelete = nil
                }
            }
            
            weak var expectationQuery2 = self.expectationWithDescription("query2")
            
            self.store.queryWithQuery(
                self.query,
                withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNotNil(results)
                    XCTAssertNil(error)
                    
                    expectationQuery2?.fulfill()
                },
                withProgressBlock: nil
            )
            
            self.waitForExpectationsWithTimeout(self.timeout) { (error: NSError?) -> Void in
                expectationQuery2 = nil
            }
        }
    }
    
}
