//
//  KCSLogTests.m
//  KinveyKit
//
//  Created by Victor Barros on 2015-05-07.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>
#import <KinveyKit/KinveyKit.h>
#import "KinveyTests-Swift.h"

@interface KCSLogTests : KCSTestCase

@property (nonatomic, strong) NSPipe* pipe;
@property (nonatomic, strong) NSMutableArray* logs;
@property (nonatomic) int stdoutCopy;
@property (nonatomic) int stderrCopy;

@end

@interface KCSLogTestsAllEnabled : KCSLogTests
@end

@interface KCSLogTestsAllDisabled : KCSLogTests
@end

@implementation KCSLogTests

- (void)setUp {
    [super setUp];
    
    self.logs = [NSMutableArray array];
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        self.stdoutCopy = dup(STDOUT_FILENO);
        self.stderrCopy = dup(STDERR_FILENO);
    });
    
    self.pipe = [NSPipe pipe];
    dup2(self.pipe.fileHandleForWriting.fileDescriptor, STDOUT_FILENO);
    dup2(self.pipe.fileHandleForWriting.fileDescriptor, STDERR_FILENO);
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleNotification:) name:NSFileHandleReadCompletionNotification object:self.pipe.fileHandleForReading];
    [self.pipe.fileHandleForReading readInBackgroundAndNotify];
}

-(void)handleNotification:(NSNotification*)notification
{
    NSString *str = [[NSString alloc] initWithData:notification.userInfo[NSFileHandleNotificationDataItem]
                                          encoding:NSUTF8StringEncoding];
    [self.logs addObject:str];
    NSFileHandle* fileHandleForReading = notification.object;
    [fileHandleForReading readInBackgroundAndNotify];
}

- (void)tearDown {
    [[NSNotificationCenter defaultCenter] removeObserver:self name:NSFileHandleReadCompletionNotification object:self.pipe.fileHandleForReading];
    
    dup2(self.stdoutCopy, STDOUT_FILENO);
    dup2(self.stderrCopy, STDERR_FILENO);
    
    [self.pipe.fileHandleForWriting closeFile];
    [self.pipe.fileHandleForReading closeFile];
    
    [self.logs removeAllObjects];
    
    [[KCSUser activeUser] logout];
    
    NSLog(@"Test");
    
    [super tearDown];
}

@end

@implementation KCSLogTestsAllEnabled

- (void)testAllEnabled {
    [KCSClient configureLoggingWithNetworkEnabled:YES
                                     debugEnabled:YES
                                     traceEnabled:YES
                                   warningEnabled:YES
                                     errorEnabled:YES];
    
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"kid_-1WAs8Rh2"
                                                 withAppSecret:@"2f355bfaa8cb4f7299e914e8e85d8c98"
                                                  usingOptions:nil];
    
    __weak XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    [KCSUser createAutogeneratedUser:nil
                          completion:^(KCSUser *user, NSError *errorOrNil, KCSUserActionResult result)
    {
        [expectationLogin fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:nil];
    
    KCSQueryTests* test = [[KCSQueryTests alloc] init];
    [test testRemoveByQuery];
    [test testQueryByDate];
    
    __weak __block XCTestExpectation *expectationLogVersion = [self expectationWithDescription:@"logVersion"];
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
        [KCS_DDLog flushLog];
        
        while (expectationLogVersion && self.logs.count < 1) {
        }
        
        XCTAssertTrue([self.logs[0] containsString:@"Kinvey iOS Library Version"], @"Actual Result: %@", self.logs.lastObject);
        
        [expectationLogVersion fulfill];
    });
    [self waitForExpectationsWithTimeout:60 handler:^(NSError *error) {
        expectationLogVersion = nil;
    }];
}

@end

@implementation KCSLogTestsAllDisabled

- (void)testAllDisabled {
    [KCSClient configureLoggingWithNetworkEnabled:NO
                                     debugEnabled:NO
                                     traceEnabled:NO
                                   warningEnabled:NO
                                     errorEnabled:NO];
    
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"kid_-1WAs8Rh2"
                                                 withAppSecret:@"2f355bfaa8cb4f7299e914e8e85d8c98"
                                                  usingOptions:nil];
    
    __weak XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    [KCSUser createAutogeneratedUser:nil
                          completion:^(KCSUser *user, NSError *errorOrNil, KCSUserActionResult result)
     {
         [expectationLogin fulfill];
     }];
    [self waitForExpectationsWithTimeout:30 handler:nil];
    
    KCSQueryTests* test = [[KCSQueryTests alloc] init];
    [test testRemoveByQuery];
    [test testQueryByDate];
    
    __weak XCTestExpectation *expectationLogVersion = [self expectationWithDescription:@"logVersion"];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(10 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [expectationLogVersion fulfill];
    });
    [self waitForExpectationsWithTimeout:60 handler:nil];
    XCTAssertEqual(self.logs.count, 0);
}

@end
