//
//  KCSQueryTests.swift
//  KinveyKit
//
//  Created by Victor Barros on 2015-04-06.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

import UIKit
import XCTest

class KCSQueryTests: XCTestCase {

    override func setUp() {
        super.setUp()
        
        setupKCS(true)
    }

    func testRemoveByQuery() {
        let collection = KCSCollection(fromString: "city", ofClass: NSMutableDictionary.self)
        let store = KCSCachedStore(collection: collection, options: [
            KCSStoreKeyCachePolicy : KCSCachePolicy.LocalFirst.rawValue,
            KCSStoreKeyOfflineUpdateEnabled : true
        ])
        
        let expectationSave = expectationWithDescription("save")
        let expectationRemove = expectationWithDescription("Remove")
        
        store.saveObject(
            [ "name" : "Vancouver" ],
            withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNil(error)
                XCTAssertNotNil(results)
                
                XCTAssertTrue(NSThread.isMainThread())
                
                dispatch_async(dispatch_get_main_queue(), { () -> Void in
                    let query = KCSQuery(onField: "name", withExactMatchForValue: "Vancouver")
                    store.removeObject(
                        query,
                        withCompletionBlock: { (count: UInt, error: NSError!) -> Void in
                            XCTAssertNil(error)
                            XCTAssertGreaterThan(count, 0 as UInt)
                            
                            expectationRemove.fulfill()
                        },
                        withProgressBlock: nil
                    )
                })
                
                expectationSave.fulfill()
            },
            withProgressBlock: nil
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }
    
    func testQueryByDate() {
        KCSUser.activeUser().logout()
        
        let expectationLogin = expectationWithDescription("login")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                expectationLogin.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
        
        let collection = KCSCollection(
            fromString: "city",
            ofClass: NSMutableDictionary.self
        )
        let store = KCSCachedStore(
            collection: collection,
            options: nil
        )
        
        let expectationSave = expectationWithDescription("save")
        
        store.saveObject(
            [
                "name" : "Vancouver",
                "info" : [
                    "settled" : NSDate(timeIntervalSince1970: -10707811.200)
                ]
            ],
            withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNotNil(results)
                XCTAssertNil(error)
                
                expectationSave.fulfill()
            },
            withProgressBlock: nil
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
        
        let expectationQuery = expectationWithDescription("query")
        
        let query = KCSQuery(onField: "info.settled", usingConditional: KCSQueryConditional.KCSLessThanOrEqual, forValue: NSDate(timeIntervalSince1970: -10697788.800))
        query.addQueryOnField("_acl.creator", withExactMatchForValue: KCSUser.activeUser().userId)
        store.queryWithQuery(
            query,
            withCompletionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNotNil(results)
                XCTAssertNil(error)
                XCTAssertEqual(results.count, 1)
                
                expectationQuery.fulfill()
            },
            withProgressBlock: nil
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }

}
