//
//  KCSTestCase.m
//  KinveyKit
//
//  Created by Victor Barros on 2015-08-14.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

#import "KCSTestCase.h"
#import "KCS_DDLog.h"
#import "KCSHiddenMethods.h"
#import "KCSURLProtocol.h"

@implementation KCSTestCase

-(void)setUp
{
    [super setUp];
    
    [KCSRequest2 cancelAndWaitUntilAllOperationsAreFinished];
    [KCSFileRequestManager cancelAndWaitUntilAllOperationsAreFinished];
    [KCSAppdataStore cancelAndWaitUntilAllOperationsAreFinished];
    
    for (Class clazz in [KCSURLProtocol protocolClasses]) {
        [KCSURLProtocol unregisterClass:clazz];
    }
    
    [KCS_DDLog flushLog];
}

-(void)tearDown
{
    [KCSRequest2 cancelAndWaitUntilAllOperationsAreFinished];
    [KCSFileRequestManager cancelAndWaitUntilAllOperationsAreFinished];
    [KCSAppdataStore cancelAndWaitUntilAllOperationsAreFinished];
    
    for (Class clazz in [KCSURLProtocol protocolClasses]) {
        [KCSURLProtocol unregisterClass:clazz];
    }
    
    [KCS_DDLog flushLog];
    
    [super tearDown];
}

-(void)setupKCS
{
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"kid_-1WAs8Rh2"
                                                 withAppSecret:@"2f355bfaa8cb4f7299e914e8e85d8c98"
                                                  usingOptions:nil];
}

-(KCSUser*)createAutogeneratedUser
{
    __weak __block XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    __block KCSUser *user = nil;
    
    [KCSUser createAutogeneratedUser:nil
                          completion:^(KCSUser *_user, NSError *errorOrNil, KCSUserActionResult result)
    {
        XCTAssertNil(errorOrNil);
        XCTAssertNotNil(_user);
        
        user = _user;
        
        [expectationLogin fulfill];
    }];
    
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationLogin = nil;
    }];
    
    return user;
}

@end
