//
//  KCSTestCase.m
//  KinveyKit
//
//  Created by Victor Barros on 2015-08-14.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

#import "KCSTestCase.h"
#import "KCS_DDLog.h"
#import "KCSHiddenMethods.h"
#import "KCSURLProtocol.h"

@interface KCSTestCase_CreateUser_MockURLProtocol : NSURLProtocol

@end

@implementation KCSTestCase

-(void)setUp
{
    [super setUp];
    
    [KCSHttpRequest cancelAndWaitUntilAllOperationsAreFinished];
    [KCSFileRequestManager cancelAndWaitUntilAllOperationsAreFinished];
    [KCSAppdataStore cancelAndWaitUntilAllOperationsAreFinished];
    
    for (Class clazz in [KCSURLProtocol protocolClasses]) {
        [KCSURLProtocol unregisterClass:clazz];
    }
    
    [KCS_DDLog flushLog];
}

-(void)tearDown
{
    [KCSHttpRequest cancelAndWaitUntilAllOperationsAreFinished];
    [KCSFileRequestManager cancelAndWaitUntilAllOperationsAreFinished];
    [KCSAppdataStore cancelAndWaitUntilAllOperationsAreFinished];
    
    for (Class clazz in [KCSURLProtocol protocolClasses]) {
        [KCSURLProtocol unregisterClass:clazz];
    }
    
    [KCS_DDLog flushLog];
    
    [KCSObjectCache setDeltaCacheBlock:nil];
    
    [super tearDown];
}

-(void)setupKCS
{
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"kid_-1WAs8Rh2"
                                                 withAppSecret:@"2f355bfaa8cb4f7299e914e8e85d8c98"
                                                  usingOptions:nil];
    self.masterSecret = @"21a9d07103c6462cb66cac1957c9ecaf";
}

-(KCSUser*)createAutogeneratedUser
{
    __weak __block XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    __block KCSUser *user = nil;
    
    [KCSUser createAutogeneratedUser:nil
                          completion:^(KCSUser *_user, NSError *errorOrNil, KCSUserActionResult result)
    {
        XCTAssertNil(errorOrNil);
        XCTAssertNotNil(_user);
        
        user = _user;
        
        [expectationLogin fulfill];
    }];
    
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationLogin = nil;
    }];
    
    return user;
}

-(void)setupClient
{
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"appKey"
                                                 withAppSecret:@"appSecret"
                                                  usingOptions:nil];
}

-(void)createUser
{
    [KCSURLProtocol registerClass:[KCSTestCase_CreateUser_MockURLProtocol class]];
    
    @try {
        XCTestExpectation* expectationLogin = [self expectationWithDescription:@"Login"];
        
        [KCSUser createAutogeneratedUser:nil
                              completion:^(KCSUser *user, NSError *errorOrNil, KCSUserActionResult result)
        {
            XCTAssertNotNil(user);
            XCTAssertNil(errorOrNil);
            
            [expectationLogin fulfill];
        }];
        
        [self waitForExpectationsWithTimeout:30 handler:nil];
        
        XCTAssertNotNil([KCSUser activeUser]);
    } @finally {
        [KCSURLProtocol unregisterClass:[KCSTestCase_CreateUser_MockURLProtocol class]];
    }
}

-(void)removeAndLogoutActiveUser:(NSTimeInterval)timeout
{
    KCSUser* user = [KCSUser activeUser];
    if (user) {
        __block __weak XCTestExpectation* expectationRemove = [self expectationWithDescription:@"remove"];
        
        [user removeWithCompletionBlock:^(NSArray *objectsOrNil, NSError *errorOrNil) {
            [expectationRemove fulfill];
        }];
        
        [self waitForExpectationsWithTimeout:timeout handler:^(NSError * _Nullable error) {
            expectationRemove = nil;
        }];
        
        [user logout];
    }
}

@end

@implementation KCSTestCase_CreateUser_MockURLProtocol

+(BOOL)canInitWithRequest:(NSURLRequest *)request
{
    return YES;
}

+(NSURLRequest *)canonicalRequestForRequest:(NSURLRequest *)request
{
    return request;
}

-(void)startLoading
{
    NSHTTPURLResponse* response = [[NSHTTPURLResponse alloc] initWithURL:self.request.URL
                                                              statusCode:200
                                                             HTTPVersion:@"1.1"
                                                            headerFields:@{ @"Content-Type" : @"application/json; charset=utf-8" }];
    [self.client URLProtocol:self
          didReceiveResponse:response
          cacheStoragePolicy:NSURLCacheStorageNotAllowed];
    NSDictionary* responseBody = @{
        @"_id" : @"my-user-id",
        @"username" : @"my-username",
        @"_kmd" : @{
            @"lmt" : @"2016-10-19T21:06:17.367Z",
            @"ect" : @"2016-10-19T21:06:17.367Z",
            @"authtoken" : @"5eba0099-0aa9-4b76-861e-29eb329712d6.jS639h+tTHiPhFUtU1RZxpH/srAiIk/cE96LDSuLbxY="
        },
        @"_acl" : @{
            @"creator" : @"5807e049b990b8b77b57ab3b"
        }
    };
    NSError* error = nil;
    NSData* data = [NSJSONSerialization dataWithJSONObject:responseBody
                                                   options:0
                                                     error:&error];
    if (error) @throw error;
    [self.client URLProtocol:self
                 didLoadData:data];
    [self.client URLProtocolDidFinishLoading:self];
}

-(void)stopLoading
{
}

@end
