//
//  KCSUserTests.swift
//  KinveyKit
//
//  Created by Victor Barros on 2015-08-10.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

import UIKit
import XCTest

class KCSUserTests: XCTestCase {

    override func setUp() {
        super.setUp()
        
        KCSClient.sharedClient().initializeKinveyServiceForAppKey(
            "kid_-1WAs8Rh2",
            withAppSecret: "2f355bfaa8cb4f7299e914e8e85d8c98",
            usingOptions: nil
        )
    }
    
    override func tearDown() {
        KCSUser.activeUser()?.logout()
        
        super.tearDown()
    }

    func testCreateAutogeneratedUser() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }
    
    func testRefreshUser() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
        
        weak var expectationRefresh = expectationWithDescription("refresh")
        
        KCSUser.activeUser().refreshFromServer { (result: [AnyObject]!, error: NSError!) -> Void in
            XCTAssertTrue(NSThread.isMainThread())
            
            expectationRefresh?.fulfill()
        }
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }
    
    func testChangePassword() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
        
        weak var expectationChangePassword = expectationWithDescription("changePassword")
        
        KCSUser.activeUser().changePassword(
            "1234",
            completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationChangePassword?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }
    
    func testSaveUser() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
        
        weak var expectationSaveUser = expectationWithDescription("saveUser")
        
        KCSUser.activeUser().saveWithCompletionBlock { (results: [AnyObject]!, error: NSError!) -> Void in
            XCTAssertTrue(NSThread.isMainThread())
            
            expectationSaveUser?.fulfill()
        }
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }
    
    func testDeleteUser() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: nil)
        
        weak var expectationDeleteUser = expectationWithDescription("deleteUser")
        
        KCSUser.activeUser().removeWithCompletionBlock { (results: [AnyObject]!, error: NSError!) -> Void in
            XCTAssertTrue(NSThread.isMainThread())
            
            expectationDeleteUser?.fulfill()
        }
        
        waitForExpectationsWithTimeout(30, handler: nil)
    }

}
