#!/bin/bash

## Prepare the ios-lib documentation.  Right now just use appledoc, but soon-ish
## use both appledoc and doxygen.

## The output/input locations are passed in via command line
if [ $# -lt 1 ]
then
	echo "Usage: build-doc <KinveyKit Location>"
	exit
fi
KINVEYKITLOC=$1

echo "Building docs for ${KINVEYKITLOC}..."

APPLEDOC=${HOME}/bin/appledoc
COMPANY=Kinvey
PROJECT=KinveyKit
COMPANYID="com.kinvey"


## Make HTML (-h), Make Docset (-d), Prep Docset for publishing (-u)
OUTPUTARGS="-h -d -u"

EXCLUDES="--ignore 3rdParty"

WARNINGS="--no-warn-invalid-crossref"
OUTPUTLOC="${KINVEYKITLOC}/doc/"
TEXTOUT="${OUTPUTLOC}/output"
DOCOUT="${OUTPUTLOC}/built-docs"

LICENSES="--include ${KINVEYKITLOC}/LICENSES.html"

if [ ! -d $OUTPUTLOC ]
then
	mkdir -p -m 775 $OUTPUTLOC
fi

if [ ! -d $TEXTOUT ]
then
	mkdir -m 775 $TEXTOUT
fi

if [ ! -d $DOCOUT ]
then
	mkdir -m 775 $DOCOUT
fi

if [ ! -d $DOCOUT ]
then
	## Last check, if this doesn't exist, bail...
	echo "!!! Unable to verify output directories... exiting..."
	exit
fi


COMMAND="${APPLEDOC} ${OUTPUTARGS} ${WARNINGS} -o ${TEXTOUT} --docset-install-path ${DOCOUT} -p ${PROJECT} -c ${COMPANY} --company-id ${COMPANYID} ${EXCLUDES} ${LICENSES} ${KINVEYKITLOC}/KinveyKit"


$COMMAND


echo "Done!"
