#!/bin/bash

## Prepare the ios-lib documentation.  Right now just use appledoc, but soon-ish
## use both appledoc and doxygen.

## The output/input locations are passed in via command line
if [ $# -lt 1 ]
then
	echo "Usage: build-kinvey <KinveyKit Location>"
	exit
fi
KINVEYKITLOC=$1

echo "Building KinveyKit in ${KINVEYKITLOC}..."

(cd $KINVEYKITLOC && xcodebuild -configuration Debug clean build)
(cd $KINVEYKITLOC && xcodebuild -configuration Release clean build)
