//
//  KCSUser2+KinveyUserService.h
//  KinveyKit
//
//  Copyright (c) 2013 Kinvey. All rights reserved.
//
// This software is licensed to you under the Kinvey terms of service located at
// http://www.kinvey.com/terms-of-use. By downloading, accessing and/or using this
// software, you hereby accept such terms of service  (and any agreement referenced
// therein) and agree that you have read, understand and agree to be bound by such
// terms of service and are of legal age to agree to such terms with Kinvey.
//
// This software contains valuable confidential and proprietary information of
// KINVEY, INC and is subject to applicable licensing agreements.
// Unauthorized reproduction, transmission or distribution of this file and its
// contents is a violation of applicable laws.
//

#import <KinveyKit/KinveyKit.h>

#import "KCSUser2.h"

typedef void (^KCSUser2CompletionBlock)(id<KCSUser2>user, NSError* error);

@interface KCSUser2 (KinveyUserService)

+ (id<KCSUser2>) activeUser;
+ (BOOL) hasSavedCredentials;
+ (BOOL) clearSavedCredentials;

+ (void) createAutogeneratedUser:(NSDictionary*)fieldsAndValues completion:(KCSUser2CompletionBlock)completionBlock;
+ (void) createUserWithUsername:(NSString*)username password:(NSString*)password fieldsAndValues:(NSDictionary*) fieldsAndValues completion:(KCSUser2CompletionBlock)completionBlock;

+ (void) loginWithUsername:(NSString *)username password:(NSString *)password completion:(KCSUser2CompletionBlock)completionBlock;
+ (void) connectWithAuthProvider:(KCSUserSocialIdentifyProvider)provider accessDictionary:(NSDictionary*)accessDictionary completionBlock:(KCSUser2CompletionBlock)completionBlock;
+ (void) logoutUser:(id<KCSUser2>)user;


+ (void) changePasswordForUser:(id<KCSUser2>)user password:(NSString*)newPassword completionBlock:(KCSUser2CompletionBlock)completionBlock;

@end
